### PR TITLE
.NET 8 & simpler syntax

### PR DESCRIPTION
**Pull request by Regenhardt**
I'm updating the todo-cli, which uses the first inquirerCS, so naturally I'm looking to update to one built with .NET Core. Might as well update to .NET 8 while I'm here.

### CODE REVIEW

**Comment by Regenhardt** [comment]
Oh and i also removed Microsoft.Graph from the dependencies, not sure what that was doing there.

**Comment by Regenhardt** [comment]
@hayer I just realized this is a breaking change, should I change the version? Not sure whether you continuously push your master to nuget.

**Comment by hayer** [comment]
I haven't pushed to this in a while. The `Microsoft.Graph` dependency was for some prototyping that should have been pushed, sorry for the confusion.

**Comment by Regenhardt** [comment]
Should I put the `Microsoft.Graph` dependencies back in? The todo-cli I'm updating uses it too, so I don't really mind the extra dependency in this case.

**Comment by hayer** [comment]
@Regenhardt I don't have much time to fix things before the weekend, sorry.

**Pull request merged**
